{
 "title": "Pironman 5 Dashboard (Business)",
 "description": "The Grafana dashboard, developed by Pironman, is a much more effective and attractive alternative to the interface displayed by the \"pm_dashboard\" Python-based application, which instantly transfers sensor data to influxDB.\n\nDeveloped by FXerkan - https://github.com/fxerkan/pironman_grafana_dashboard",
 "tags": [
  "Pironman 5",
  "influxdb",
  "Raspberry Pi"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prm_server_url", "label": "Raspberry Server URL", "query": "192.168.1.62:34001" },
   {
    "name": "prm_rgb_style",
    "label": "RGB Style",
    "query": "none, solid, breathing, flow, flow_reverse, rainbow, rainbow_reverse, hue_cycle"
   },
   { "name": "prm_rgb_speed", "label": "RGB Speed", "query": "0,1,5,10,15,20,25,50,75,100" },
   { "name": "prm_rgb_color", "label": "RGB Color", "query": "#0a1aff, #42ff30, #ff130f" },
   { "name": "prm_rgb_brightness", "label": "RGB Brightness", "query": "1,5,10,15,20,25,50,75,100" },
   { "name": "prm_oled_sleep_timeout", "label": "OLEP Sleep", "query": "0,1,5,10,15,20,25,30,60,90,120" },
   { "name": "prm_oled_disk", "label": "OLED Disk", "query": { "query": "" } },
   { "name": "prm_oled_network", "label": "OLED Network", "query": { "query": "" } },
   {
    "name": "prm_gpio_fan_mode",
    "label": "GPIO Fan Mode",
    "query": "Quite : 4, Balanced : 3, Cool : 2, Performance : 1, Always_on : 0"
   },
   { "name": "prm_logs", "label": "Logs File", "query": { "query": "" } },
   {
    "name": "prm_log_level",
    "label": "Log Level",
    "query": "INFO, WARNING, ERROR, DEBUG, CRITICAL"
   },
   {
    "name": "prm_log_lines",
    "label": "Log Lines",
    "query": "200, 500, 1000, 2000, 5000, 10000"
   }
  ]
 },
 "panels": [
  {
   "title": "Settings - RGB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RGB Led",
     "type": "canvas",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
     "targets": [
      {
       "columns": [
        { "selector": "rgb_enable", "text": "", "type": "boolean" }
       ],
       "parser": "backend",
       "root_selector": "data.system",
       "source": "url",
       "type": "json",
       "url": "get-config",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "RGB Style",
     "type": "volkovlabs-variable-panel",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "targets": [
      {}
     ]
    },
    {
     "title": "RGB Brightness",
     "type": "volkovlabs-variable-panel",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
     "targets": [
      {}
     ]
    },
    {
     "title": "RGB Speed",
     "type": "volkovlabs-variable-panel",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
     "targets": [
      {}
     ]
    },
    {
     "title": "RGB Color",
     "type": "volkovlabs-variable-panel",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
     "targets": [
      {}
     ]
    },
    {
     "title": "RGB Style",
     "type": "canvas",
     "description": "Please do not forget to first select the value/option in the \"RGB Style\" variable from the variables bar at the top to use the \"Change\" button.",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
     "targets": [
      {
       "columns": [
        { "selector": "rgb_style", "text": "", "type": "string" }
       ],
       "parser": "backend",
       "root_selector": "data.system",
       "source": "url",
       "type": "json",
       "url": "get-config",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "RGB Brightness",
     "type": "canvas",
     "description": "Please do not forget to first select the value/option in the \"RGB Brightness\" variable from the variables bar at the top to use the \"Change\" button.",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
     "targets": [
      {
       "columns": [
        { "selector": "rgb_brightness", "text": "", "type": "string" }
       ],
       "parser": "backend",
       "root_selector": "data.system",
       "source": "url",
       "type": "json",
       "url": "get-config",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "RGB Speed",
     "type": "canvas",
     "description": "Please do not forget to first select the value/option in the \"RGB Speed\" variable from the variables bar at the top to use the \"Change\" button.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
     "targets": [
      {
       "columns": [
        { "selector": "rgb_speed", "text": "", "type": "string" }
       ],
       "parser": "backend",
       "root_selector": "data.system",
       "source": "url",
       "type": "json",
       "url": "get-config",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "RGB Color",
     "type": "canvas",
     "description": "Please do not forget to first select the value/option in the \"RGB Style\" variable from the variables bar at the top to use the \"Change\" button.\n\nSet RGB color fixed color only available if RGB Style = \"Solid\"",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
     "targets": [
      {
       "columns": [
        { "selector": "rgb_color", "text": "", "type": "string" }
       ],
       "parser": "backend",
       "root_selector": "data.system",
       "source": "url",
       "type": "json",
       "url": "get-config",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  },
  {
   "title": "Settings - OLED",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "OLED",
     "type": "canvas",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
     "targets": [
      {
       "columns": [
        { "selector": "oled_enable", "text": "", "type": "boolean" }
       ],
       "parser": "backend",
       "root_selector": "data.system",
       "source": "url",
       "type": "json",
       "url": "get-config",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "OLED Sleep Timeout",
     "type": "volkovlabs-variable-panel",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
     "targets": [
      {}
     ]
    },
    {
     "title": "OLED Disc",
     "type": "volkovlabs-variable-panel",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
     "targets": [
      {}
     ]
    },
    {
     "title": "OLED Network Interface",
     "type": "volkovlabs-variable-panel",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Data Interval",
     "type": "canvas",
     "description": "Frequency of writing/reading sensor data to influxDB",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "columns": [
        { "selector": "data_interval", "text": "", "type": "string" }
       ],
       "parser": "backend",
       "root_selector": "data.system",
       "source": "url",
       "type": "json",
       "url": "get-config",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "OLED Rotation",
     "type": "canvas",
     "description": "Please do not forget to first select the value/option in the \"OLED Rotation\" variable from the variables bar at the top to use the \"Change\" button.",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
     "targets": [
      {
       "columns": [
        { "selector": "oled_rotation", "text": "", "type": "number" }
       ],
       "parser": "backend",
       "root_selector": "data.system",
       "source": "url",
       "type": "json",
       "url": "get-config",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "OLED Sleep Timeout",
     "type": "canvas",
     "description": "Please do not forget to first select the value/option in the \"OLED Speed Timeout\" variable from the variables bar at the top to use the \"Change\" button.",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "columns": [
        { "selector": "oled_sleep_timeout", "text": "", "type": "number" }
       ],
       "parser": "backend",
       "root_selector": "data.system",
       "source": "url",
       "type": "json",
       "url": "get-config",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "OLED Disk",
     "type": "canvas",
     "description": "Please do not forget to first select the value/option in the \"OLED Disk\" variable from the variables bar at the top to use the \"Change\" button.\n\nSets which Disc's capacity and usage information will be displayed on the OLED screen.",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
     "targets": [
      {
       "columns": [
        { "selector": "oled_disk", "text": "", "type": "string" }
       ],
       "parser": "backend",
       "root_selector": "data.system",
       "source": "url",
       "type": "json",
       "url": "get-config",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "OLED Network",
     "type": "canvas",
     "description": "Please do not forget to first select the value/option in the \"OLED Network\" variable from the variables bar at the top to use the \"Change\" button.\n\nSets which Network Interface information will be displayed on the OLED screen.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
     "targets": [
      {
       "columns": [
        { "selector": "oled_network_interface", "text": "", "type": "string" }
       ],
       "parser": "backend",
       "root_selector": "data.system",
       "source": "url",
       "type": "json",
       "url": "get-config",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Debug Level",
     "type": "canvas",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
     "targets": [
      {
       "columns": [
        { "selector": "debug_level", "text": "", "type": "string" }
       ],
       "parser": "backend",
       "root_selector": "data.system",
       "source": "url",
       "type": "json",
       "url": "get-config",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  },
  {
   "title": "Settings - Fan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fan Led",
     "type": "canvas",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
     "targets": [
      {
       "columns": [
        { "selector": "gpio_fan_led", "text": "", "type": "string" }
       ],
       "parser": "backend",
       "root_selector": "data.system",
       "source": "url",
       "type": "json",
       "url": "get-config",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "GPIO Fan Mode",
     "type": "volkovlabs-variable-panel",
     "gridPos": { "h": 3, "w": 6, "x": 3, "y": 3 },
     "targets": [
      {}
     ]
    },
    {
     "title": "GPIO Fan Mode",
     "type": "canvas",
     "description": "Please do not forget to first select the value/option in the \"GPIO Fan Mode\" variable from the variables bar at the top to use the \"Change\" button.",
     "gridPos": { "h": 3, "w": 6, "x": 3, "y": 6 },
     "targets": [
      {
       "columns": [
        { "selector": "gpio_fan_mode", "text": "", "type": "string" }
       ],
       "parser": "backend",
       "root_selector": "data.system",
       "source": "url",
       "type": "json",
       "url": "get-config",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  },
  { "title": "Pironman 5 Dashboard (Overall)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PWM Fan Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "pwm_fan_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Memory %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "memory_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disc %",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SD Card %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "limit": "1",
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/mmcblk0_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "NVME SSD %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "limit": "1",
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/nvme0n1_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "USB Disc %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "limit": "1",
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/sda_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "query": "SELECT moving_average(mean(\"network_download_speed\"), 10) * -1 FROM \"history\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "network_download_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "network_upload_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "GPIO Fan State (On/Off)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "gpio_fan_state" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PWM Fan Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "pwm_fan_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "gpu_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "gpu_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPUs",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 28 },
   "targets": [
    {
     "limit": "1",
     "measurement": "history",
     "query": "SELECT \n       last(\"cpu_count\") as \"# CPU Cores\" ,\n       median(\"cpu_freq\") as \"CPU Frequency\", \n       last(\"cpu_freq_min\") as \"CPU Frequency - Min\",\n       last(\"cpu_freq_max\") as \"CPU Frequency - Max\"\nFROM \"history\" \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "cpu_freq" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "query": "SELECT moving_average(mean(\"cpu_0_percent\"), 10) FROM \"history\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "cpu_0_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "CPU 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_1_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "CPU 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_2_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "CPU 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_3_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "RAM",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 37 },
   "targets": [
    {
     "limit": "1",
     "measurement": "history",
     "query": "SELECT \n       last(\"memory_percent\") as \"Memory %\" ,\n       median(\"memory_used\") /1024/1024 as \"Used Memory (GB)\", \n       last(\"memory_available\") /1024/1024 as \"Available Memory (GB)\",\n       last(\"memory_total\") /1024/1024 as \"Total Memory (GB)\"\nFROM \"history\" \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "cpu_freq" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Memory %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "memory_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Used Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "memory_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Available Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "memory_available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Network",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 46 },
   "targets": [
    {
     "limit": "1",
     "measurement": "history",
     "query": "SELECT \n      last(\"network_type\") as \"Network Type(s)\" ,\n       last(\"mac_wlan0\") as \"WiFi MAC\", \n       last(\"ip_wlan0\") as \"WiFi IP\", \n       last(\"mac_end0\") as \"Ethernet MAC\",\n       last(\"ip_end0\") as \"Ethernet IP\",\n       last(\"mac_docker0\")  as \"Docker MAC\",\n       last(\"ip_docker0\")  as \"Docker IP\",\n       last(\"mac_lxcbr0\")  as \"Lxcbr MAC\",\n       last(\"ip_lxcbr0\")  as \"Lxcbr IP\",\n       last(\"mac_tailscale0\")  as \"Tailscale MAC\",\n       last(\"ip_tailscale0\")  as \"Tailscale IP\"\nFROM \"history\" \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "cpu_freq" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "query": "SELECT moving_average(mean(\"network_download_speed\"), 10) * -1 FROM \"history\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "network_download_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "network_upload_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "SD Card Mounted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/mmcblk0_mounted" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SD Card %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SD Card %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/mmcblk0_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SD Card Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "query": "SELECT moving_average(mean(\"cpu_0_percent\"), 10) FROM \"history\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "disk_/dev/mmcblk0_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/mmcblk0_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/mmcblk0_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVME SSD Mounted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/nvme0n1_mounted" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVME SSD %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "NVME SSD %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/nvme0n1_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVME SSD Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "query": "SELECT moving_average(mean(\"cpu_0_percent\"), 10) FROM \"history\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "disk_/dev/nvme0n1_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/nvme0n1_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/nvme0n1_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "USB Disc Mounted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/sda_mounted" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "USB Disc %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "USB Disc %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/sda_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "USB Disc Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "query": "SELECT moving_average(mean(\"cpu_0_percent\"), 10) FROM \"history\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "disk_/dev/sda_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/sda_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/sda_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs File",
     "type": "volkovlabs-variable-panel",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 292 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Log Details (${prm_logs})",
     "type": "table",
     "gridPos": { "h": 20, "w": 19, "x": 5, "y": 292 },
     "targets": [
      {
       "json_options": {
        "columnar": false,
        "root_is_not_array": false
       },
       "parser": "simple",
       "root_selector": "data",
       "source": "url",
       "type": "json",
       "url": "get-log?filename=${prm_logs}&filter=&lines=${prm_log_lines}&level=${prm_log_level}",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "# Logs by Level",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 5, "x": 0, "y": 299 },
     "targets": [
      {
       "json_options": {
        "columnar": false,
        "root_is_not_array": false
       },
       "parser": "simple",
       "root_selector": "data",
       "source": "url",
       "type": "json",
       "url": "get-log?filename=${prm_logs}&filter=&lines=${prm_log_lines}&level=${prm_log_level}",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  }
 ]
}