{
 "title": "Pironman 5 Dashboard (Simple)",
 "description": "Grafana Dashboard to showing the influxdb time series data populated by Pironman 5 (as an alternative of the pm_dashboard) by FXerkan.\nhttps://github.com/fxerkan",
 "tags": [
  "Pironman 5",
  "influxdb",
  "Raspberry Pi"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pironman 5 Max Dashboard (Overall)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PWM Fan Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "pwm_fan_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Memory %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "memory_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SD Card %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SD Card %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/mmcblk0_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVME SSD %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SD Card %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/nvme0n1_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "query": "SELECT moving_average(mean(\"network_download_speed\"), 10) * -1 FROM \"history\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "network_download_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "network_upload_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "GPIO Fan State (On/Off)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "gpio_fan_state" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PWM Fan Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "pwm_fan_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "gpu_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "gpu_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPUs",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 25 },
   "targets": [
    {
     "limit": "1",
     "measurement": "history",
     "query": "SELECT \n       last(\"cpu_count\") as \"# CPU Cores\" ,\n       median(\"cpu_freq\") as \"CPU Frequency\", \n       last(\"cpu_freq_min\") as \"CPU Frequency - Min\",\n       last(\"cpu_freq_max\") as \"CPU Frequency - Max\"\nFROM \"history\" \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "cpu_freq" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "query": "SELECT moving_average(mean(\"cpu_0_percent\"), 10) FROM \"history\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "cpu_0_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "CPU 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_1_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "CPU 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_2_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "CPU 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "cpu_3_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "RAM",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 34 },
   "targets": [
    {
     "limit": "1",
     "measurement": "history",
     "query": "SELECT \n       last(\"memory_percent\") as \"Memory %\" ,\n       median(\"memory_used\") /1024/1024 as \"Used Memory (GB)\", \n       last(\"memory_available\") /1024/1024 as \"Available Memory (GB)\",\n       last(\"memory_total\") /1024/1024 as \"Total Memory (GB)\"\nFROM \"history\" \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "cpu_freq" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Memory %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "memory_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Used Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "memory_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Available Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "memory_available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Network",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 43 },
   "targets": [
    {
     "limit": "1",
     "measurement": "history",
     "query": "SELECT \n      last(\"network_type\") as \"Network Type(s)\" ,\n       last(\"mac_wlan0\") as \"WiFi MAC\", \n       last(\"ip_wlan0\") as \"WiFi IP\", \n       last(\"mac_end0\") as \"Ethernet MAC\",\n       last(\"ip_end0\") as \"Ethernet IP\",\n       last(\"mac_docker0\")  as \"Docker MAC\",\n       last(\"ip_docker0\")  as \"Docker IP\",\n       last(\"mac_lxcbr0\")  as \"Lxcbr MAC\",\n       last(\"ip_lxcbr0\")  as \"Lxcbr IP\",\n       last(\"mac_tailscale0\")  as \"Tailscale MAC\",\n       last(\"ip_tailscale0\")  as \"Tailscale IP\"\nFROM \"history\" \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 1",
     "select": [
      [
       { "params": [ "cpu_freq" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "query": "SELECT moving_average(mean(\"network_download_speed\"), 10) * -1 FROM \"history\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "network_download_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "network_upload_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "SD Card Mounted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/mmcblk0_mounted" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SD Card %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SD Card %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/mmcblk0_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SD Card Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "query": "SELECT moving_average(mean(\"cpu_0_percent\"), 10) FROM \"history\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "disk_/dev/mmcblk0_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/mmcblk0_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/mmcblk0_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVME SSD Mounted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/nvme0n1_mounted" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVME SSD %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SD Card %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/nvme0n1_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVME SSD Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "query": "SELECT moving_average(mean(\"cpu_0_percent\"), 10) FROM \"history\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "disk_/dev/nvme0n1_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/nvme0n1_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/nvme0n1_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "USB Disc Mounted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/sda_mounted" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "USB Disc %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SD Card %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/sda_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "USB Disc Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "query": "SELECT moving_average(mean(\"cpu_0_percent\"), 10) FROM \"history\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "disk_/dev/sda_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/sda_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "history",
     "select": [
      [
       { "params": [ "disk_/dev/sda_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  }
 ]
}